//! UI-independent derivations for the C source-debugging views: grouping
//! machine code under the C line it came from and naming where variables live.
use vole_core::{
    Instruction,
    debug::{DebugInfo, FrameView, Location, VariableKind, VariableView},
};

/// A contiguous run of instructions produced by one C line, or by code without
/// a user line (startup, runtime or compiler-generated code).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Group {
    pub line: Option<usize>,
    /// Function containing the group, when debug information names one.
    pub function: Option<String>,
    /// True when the function belongs to the user's document.
    pub user: bool,
    /// Half-open range of disassembly indexes.
    pub start: usize,
    pub end: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MachineRow {
    Header(usize),
    Instruction { index: usize, group: usize },
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MachineLayout {
    pub rows: Vec<MachineRow>,
    pub groups: Vec<Group>,
    /// Row index of each disassembly index.
    pub instruction_rows: Vec<usize>,
}

impl MachineLayout {
    pub fn new(disassembly: &[Instruction], debug: Option<&DebugInfo>) -> Self {
        let mut layout = Self::default();
        for (index, instruction) in disassembly.iter().enumerate() {
            let function = debug.and_then(|d| d.function_at(instruction.address));
            let name = function.map(|f| f.name.clone());
            let user = function.is_some_and(|f| f.user);
            let starts_group = layout.groups.last().is_none_or(|group| {
                group.line != instruction.source_line || group.function != name
            });
            if starts_group {
                layout.groups.push(Group {
                    line: instruction.source_line,
                    function: name,
                    user,
                    start: index,
                    end: index,
                });
                layout
                    .rows
                    .push(MachineRow::Header(layout.groups.len() - 1));
            }
            let group = layout.groups.len() - 1;
            layout.groups[group].end = index + 1;
            layout.instruction_rows.push(layout.rows.len());
            layout.rows.push(MachineRow::Instruction { index, group });
        }
        layout
    }

    pub fn group_of_instruction(&self, index: usize) -> Option<usize> {
        match self.rows.get(*self.instruction_rows.get(index)?)? {
            MachineRow::Instruction { group, .. } => Some(*group),
            MachineRow::Header(_) => None,
        }
    }

    /// Header row of the first group generated by `line`.
    pub fn first_header_for_line(&self, line: usize) -> Option<usize> {
        let group = self.groups.iter().position(|g| g.line == Some(line))?;
        self.rows
            .iter()
            .position(|row| *row == MachineRow::Header(group))
    }
}

/// Text for a group without a user line.
pub fn unlined_group_label(group: &Group) -> String {
    match (&group.function, group.user) {
        (Some(name), true) => format!("{name}: compiler-generated code without a C line"),
        (Some(name), false) => format!("{name}: runtime code without C source"),
        (None, _) => "Startup code without C source".into(),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ChipTarget {
    Memory { address: u64, size: u64 },
    Register(String),
}

/// Where a variable's value lives, in the compiler's own terms when possible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocationChip {
    pub text: String,
    /// Longer description for tooltips and screen readers.
    pub description: String,
    pub target: ChipTarget,
}

pub fn hex_address(address: u64) -> String {
    format!("0x{address:08X}")
}

fn signed_offset(register: &str, offset: i64) -> String {
    match offset {
        0 => format!("[{register}]"),
        offset if offset < 0 => format!("[{register}\u{2212}{}]", offset.unsigned_abs()),
        offset => format!("[{register}+{offset}]"),
    }
}

/// Resolve a location list entry for `pc`; other locations pass through.
fn at_pc(location: &Location, pc: u64) -> Option<&Location> {
    match location {
        Location::List(ranges) => ranges
            .iter()
            .find(|range| (range.start..range.end).contains(&pc))
            .and_then(|range| at_pc(&range.location, pc)),
        location => Some(location),
    }
}

/// Symbolic form of a memory location such as `[x29−4]`, or a register name.
fn symbolic(location: &Location, frame_base: Option<&Location>, pc: u64) -> Option<Symbolic> {
    match at_pc(location, pc)? {
        Location::FrameOffset(offset) => match frame_base.and_then(|base| at_pc(base, pc))? {
            Location::Register(register) => {
                Some(Symbolic::Memory(signed_offset(register, *offset)))
            }
            Location::RegisterOffset {
                register,
                offset: base,
            } => Some(Symbolic::Memory(signed_offset(register, base + offset))),
            _ => None,
        },
        Location::RegisterOffset { register, offset } => {
            Some(Symbolic::Memory(signed_offset(register, *offset)))
        }
        Location::Register(register) => Some(Symbolic::Register(register.clone())),
        Location::Address(_) => Some(Symbolic::Static),
        Location::List(_) | Location::Unavailable(_) => None,
    }
}

enum Symbolic {
    Memory(String),
    Register(String),
    Static,
}

/// Describe where `variable` lives. Frame-relative variables use the frame's
/// function from `debug`; children and globals use their address.
pub fn location_chip(
    variable: &VariableView,
    frame: Option<&FrameView>,
    debug: Option<&DebugInfo>,
) -> Option<LocationChip> {
    let memory = |text: String, description: String, address: u64| LocationChip {
        text,
        description,
        target: ChipTarget::Memory {
            address,
            size: variable.size,
        },
    };
    let symbolic = match (variable.kind, frame, debug) {
        (VariableKind::Parameter | VariableKind::Local, Some(frame), Some(debug)) => {
            debug.function_at(frame.pc).and_then(|function| {
                function
                    .variables
                    .iter()
                    .filter(|v| v.name == variable.name)
                    .find(|v| {
                        v.scope.is_empty()
                            || v.scope
                                .iter()
                                .any(|(start, end)| (*start..*end).contains(&frame.pc))
                    })
                    .and_then(|v| symbolic(&v.location, function.frame_base.as_ref(), frame.pc))
            })
        }
        _ => None,
    };
    match (symbolic, variable.address) {
        (Some(Symbolic::Register(register)), _) => Some(LocationChip {
            description: format!("Value is held in register {register}"),
            text: register.clone(),
            target: ChipTarget::Register(register),
        }),
        (Some(Symbolic::Memory(text)), Some(address)) => Some(memory(
            text.clone(),
            format!(
                "Stored at {text} = {}, {} bytes. Show in memory.",
                hex_address(address),
                variable.size
            ),
            address,
        )),
        (Some(Symbolic::Static), Some(address)) => Some(memory(
            format!("static {}", hex_address(address)),
            format!(
                "Static storage at {}, {} bytes. Show in memory.",
                hex_address(address),
                variable.size
            ),
            address,
        )),
        (_, Some(address)) if variable.kind == VariableKind::Global => Some(memory(
            format!("global {}", hex_address(address)),
            format!(
                "Global storage at {}, {} bytes. Show in memory.",
                hex_address(address),
                variable.size
            ),
            address,
        )),
        (_, Some(address)) => Some(memory(
            hex_address(address),
            format!(
                "Stored at {}, {} bytes. Show in memory.",
                hex_address(address),
                variable.size
            ),
            address,
        )),
        _ => None,
    }
}

/// Unavailable reasons read as a short sentence fragment after "unavailable: ".
pub fn unavailable_text(reason: &str) -> String {
    let reason = reason.trim().trim_end_matches('.');
    let mut chars = reason.chars();
    let reason = match chars.next() {
        Some(first) if chars.clone().next().is_some_and(|c| c.is_lowercase()) => {
            first.to_lowercase().collect::<String>() + chars.as_str()
        }
        _ => reason.to_string(),
    };
    format!("unavailable: {reason}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use vole_core::debug::{Function, LocationRange, ValueText, Variable};

    fn instruction(address: u64, line: Option<usize>) -> Instruction {
        Instruction {
            address,
            bytes: vec![0; 4],
            assembly: "nop".into(),
            explanation: String::new(),
            source_line: line,
            reads: Vec::new(),
            writes: Vec::new(),
        }
    }

    fn function(name: &str, low: u64, high: u64, user: bool, variables: Vec<Variable>) -> Function {
        Function {
            name: name.into(),
            low_pc: low,
            high_pc: high,
            decl_file: 0,
            decl_line: 1,
            frame_base: Some(Location::Register("x29".into())),
            return_type: None,
            variables,
            prologue_end: None,
            user,
        }
    }

    fn view(name: &str, kind: VariableKind, address: Option<u64>) -> VariableView {
        VariableView {
            name: name.into(),
            type_name: "int".into(),
            kind,
            value: ValueText::Value("1".into()),
            address,
            size: 4,
            children: Vec::new(),
            changed: false,
        }
    }

    #[test]
    fn groups_follow_lines_and_functions() {
        let debug = DebugInfo {
            functions: vec![
                function("_start", 0x1000, 0x1008, false, Vec::new()),
                function("main", 0x1008, 0x1020, true, Vec::new()),
            ],
            ..Default::default()
        };
        let code = [
            instruction(0x1000, None),
            instruction(0x1004, None),
            instruction(0x1008, Some(3)),
            instruction(0x100c, Some(3)),
            instruction(0x1010, Some(4)),
            instruction(0x1014, Some(3)),
        ];
        let layout = MachineLayout::new(&code, Some(&debug));
        assert_eq!(layout.groups.len(), 4);
        assert_eq!(layout.rows.len(), 10);
        assert_eq!(layout.groups[1].line, Some(3));
        assert_eq!((layout.groups[1].start, layout.groups[1].end), (2, 4));
        assert_eq!(layout.instruction_rows[4], 7);
        assert_eq!(layout.group_of_instruction(5), Some(3));
        assert_eq!(layout.first_header_for_line(3), Some(3));
        assert_eq!(
            unlined_group_label(&layout.groups[0]),
            "_start: runtime code without C source"
        );
    }

    #[test]
    fn chips_name_frame_slots_registers_and_globals() {
        let variables = vec![
            Variable {
                name: "count".into(),
                type_id: None,
                location: Location::FrameOffset(-4),
                decl_file: 0,
                decl_line: 2,
                parameter: false,
                scope: Vec::new(),
            },
            Variable {
                name: "value".into(),
                type_id: None,
                location: Location::List(vec![LocationRange {
                    start: 0x1000,
                    end: 0x1010,
                    location: Location::Register("x0".into()),
                }]),
                decl_file: 0,
                decl_line: 2,
                parameter: true,
                scope: Vec::new(),
            },
        ];
        let debug = DebugInfo {
            functions: vec![function("square", 0x1000, 0x1020, true, variables)],
            ..Default::default()
        };
        let frame = FrameView {
            index: 0,
            function: "square".into(),
            pc: 0x1004,
            cfa: None,
            location: None,
            user: true,
            variables: Vec::new(),
        };
        let chip = location_chip(
            &view("count", VariableKind::Local, Some(0x1ffdc)),
            Some(&frame),
            Some(&debug),
        )
        .unwrap();
        assert_eq!(chip.text, "[x29\u{2212}4]");
        assert_eq!(
            chip.target,
            ChipTarget::Memory {
                address: 0x1ffdc,
                size: 4
            }
        );
        let chip = location_chip(
            &view("value", VariableKind::Parameter, None),
            Some(&frame),
            Some(&debug),
        )
        .unwrap();
        assert_eq!(chip.target, ChipTarget::Register("x0".into()));
        let chip = location_chip(
            &view("total", VariableKind::Global, Some(0xa000)),
            None,
            None,
        )
        .unwrap();
        assert_eq!(chip.text, "global 0x0000A000");
        let chip = location_chip(
            &view("[1]", VariableKind::Element, Some(0x1ffe0)),
            None,
            None,
        )
        .unwrap();
        assert_eq!(chip.text, "0x0001FFE0");
        assert!(location_chip(&view("gone", VariableKind::Local, None), None, None).is_none());
    }

    #[test]
    fn unavailable_reasons_read_as_fragments() {
        assert_eq!(
            unavailable_text("Prologue not finished."),
            "unavailable: prologue not finished"
        );
        assert_eq!(
            unavailable_text("PC is outside"),
            "unavailable: PC is outside"
        );
    }
}
