//! UI-independent derivations for the C source-debugging views: grouping
//! machine code under the C line it came from and naming where variables live.
use vole_core::{
    Instruction,
    debug::{DebugInfo, Storage, VariableKind, VariableView},
};

/// A contiguous run of instructions produced by one C line, or by code without
/// a user line (startup, runtime or compiler-generated code).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Group {
    pub line: Option<usize>,
    /// Function containing the group, when debug information names one.
    pub function: Option<String>,
    /// True when the function belongs to the user's document.
    pub user: bool,
    /// Half-open range of disassembly indexes.
    pub start: usize,
    pub end: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MachineRow {
    Header(usize),
    Instruction { index: usize, group: usize },
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MachineLayout {
    pub rows: Vec<MachineRow>,
    pub groups: Vec<Group>,
    /// Row index of each disassembly index.
    pub instruction_rows: Vec<usize>,
}

impl MachineLayout {
    pub fn new(disassembly: &[Instruction], debug: Option<&DebugInfo>) -> Self {
        let mut layout = Self::default();
        for (index, instruction) in disassembly.iter().enumerate() {
            let function = debug.and_then(|d| d.function_at(instruction.address));
            let name = function.map(|f| f.name.clone());
            let user = function.is_some_and(|f| f.user);
            let starts_group = layout.groups.last().is_none_or(|group| {
                group.line != instruction.source_line || group.function != name
            });
            if starts_group {
                layout.groups.push(Group {
                    line: instruction.source_line,
                    function: name,
                    user,
                    start: index,
                    end: index,
                });
                layout
                    .rows
                    .push(MachineRow::Header(layout.groups.len() - 1));
            }
            let group = layout.groups.len() - 1;
            layout.groups[group].end = index + 1;
            layout.instruction_rows.push(layout.rows.len());
            layout.rows.push(MachineRow::Instruction { index, group });
        }
        layout
    }

    pub fn group_of_instruction(&self, index: usize) -> Option<usize> {
        match self.rows.get(*self.instruction_rows.get(index)?)? {
            MachineRow::Instruction { group, .. } => Some(*group),
            MachineRow::Header(_) => None,
        }
    }

    /// Header row of the first group generated by `line`.
    pub fn first_header_for_line(&self, line: usize) -> Option<usize> {
        let group = self.groups.iter().position(|g| g.line == Some(line))?;
        self.rows
            .iter()
            .position(|row| *row == MachineRow::Header(group))
    }
}

/// Text for a group without a user line.
pub fn unlined_group_label(group: &Group) -> String {
    match (&group.function, group.user) {
        (Some(name), true) => format!("{name}: compiler-generated code without a C line"),
        (Some(name), false) => format!("{name}: runtime code without C source"),
        (None, _) => "Startup code without C source".into(),
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ChipTarget {
    Memory { address: u64, size: u64 },
    Register(String),
}

/// Where a variable's value lives, in the compiler's own terms when possible.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LocationChip {
    pub text: String,
    /// Longer description for tooltips and screen readers.
    pub description: String,
    pub target: ChipTarget,
}

pub fn hex_address(address: u64) -> String {
    format!("0x{address:08X}")
}

fn signed_offset(register: &str, offset: i64) -> String {
    match offset {
        0 => format!("[{register}]"),
        offset if offset < 0 => format!("[{register}\u{2212}{}]", offset.unsigned_abs()),
        offset => format!("[{register}+{offset}]"),
    }
}

/// Describe where `variable` lives, using the storage the debugger resolved
/// at the frame's PC. Children and other addressed values use their address.
pub fn location_chip(variable: &VariableView) -> Option<LocationChip> {
    let memory = |text: String, description: String, address: u64| LocationChip {
        text,
        description,
        target: ChipTarget::Memory {
            address,
            size: variable.size,
        },
    };
    match (&variable.storage, variable.address) {
        (Some(Storage::Register(register)), _) => Some(LocationChip {
            description: format!("Value is held in register {register}"),
            text: register.clone(),
            target: ChipTarget::Register(register.clone()),
        }),
        (Some(Storage::RegisterOffset { register, offset }), Some(address)) => {
            let text = signed_offset(register, *offset);
            Some(memory(
                text.clone(),
                format!(
                    "Stored at {text} = {}, {} bytes. Show in memory.",
                    hex_address(address),
                    variable.size
                ),
                address,
            ))
        }
        (Some(Storage::Static), Some(address)) if variable.kind != VariableKind::Global => {
            Some(memory(
                format!("static {}", hex_address(address)),
                format!(
                    "Static storage at {}, {} bytes. Show in memory.",
                    hex_address(address),
                    variable.size
                ),
                address,
            ))
        }
        (_, Some(address)) if variable.kind == VariableKind::Global => Some(memory(
            format!("global {}", hex_address(address)),
            format!(
                "Global storage at {}, {} bytes. Show in memory.",
                hex_address(address),
                variable.size
            ),
            address,
        )),
        (_, Some(address)) => Some(memory(
            hex_address(address),
            format!(
                "Stored at {}, {} bytes. Show in memory.",
                hex_address(address),
                variable.size
            ),
            address,
        )),
        _ => None,
    }
}

/// Unavailable reasons read as a short sentence fragment after "unavailable: ".
pub fn unavailable_text(reason: &str) -> String {
    let reason = reason.trim().trim_end_matches('.');
    let mut chars = reason.chars();
    let reason = match chars.next() {
        Some(first) if chars.clone().next().is_some_and(|c| c.is_lowercase()) => {
            first.to_lowercase().collect::<String>() + chars.as_str()
        }
        _ => reason.to_string(),
    };
    format!("unavailable: {reason}")
}

/// Requested line to toggle when the user clicks the breakpoint mark of
/// `line`. A breakpoint set on a line without code snaps forward and is shown
/// on the line it resolves to; clicking there removes that stored breakpoint
/// instead of adding a second one.
pub fn breakpoint_line_to_toggle(
    line: usize,
    stored: impl IntoIterator<Item = (usize, Option<usize>)>,
) -> usize {
    let stored: Vec<_> = stored.into_iter().collect();
    if stored.iter().any(|(requested, _)| *requested == line) {
        return line;
    }
    stored
        .iter()
        .find(|(_, resolved)| *resolved == Some(line))
        .map_or(line, |(requested, _)| *requested)
}

/// Move 1-based breakpoint lines to follow an edit from `old` to `new`.
///
/// The edit is located by the longest common prefix and suffix of lines.
/// Lines before the change stay, lines after it shift by the change in line
/// count, and lines inside the changed region keep their number while it still
/// exists in the new text; lines whose text was deleted are dropped.
pub fn shift_breakpoint_lines(
    old: &str,
    new: &str,
    lines: &std::collections::BTreeSet<usize>,
) -> std::collections::BTreeSet<usize> {
    let old_lines: Vec<&str> = old.split('\n').collect();
    let new_lines: Vec<&str> = new.split('\n').collect();
    let prefix = old_lines
        .iter()
        .zip(&new_lines)
        .take_while(|(a, b)| a == b)
        .count();
    let limit = old_lines.len().min(new_lines.len()) - prefix;
    let suffix = old_lines
        .iter()
        .rev()
        .zip(new_lines.iter().rev())
        .take(limit)
        .take_while(|(a, b)| a == b)
        .count();
    let old_end = old_lines.len() - suffix;
    let new_region = new_lines.len() - suffix - prefix;
    let delta = new_lines.len() as isize - old_lines.len() as isize;
    lines
        .iter()
        .filter_map(|line| {
            let index = line.checked_sub(1)?;
            if index < prefix {
                Some(*line)
            } else if index >= old_end {
                usize::try_from(index as isize + delta).ok().map(|i| i + 1)
            } else if index - prefix < new_region {
                Some(*line)
            } else {
                None
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use vole_core::debug::{Function, Location, ValueText, Variable};

    fn instruction(address: u64, line: Option<usize>) -> Instruction {
        Instruction {
            address,
            bytes: vec![0; 4],
            assembly: "nop".into(),
            explanation: String::new(),
            source_line: line,
            reads: Vec::new(),
            writes: Vec::new(),
        }
    }

    fn function(name: &str, low: u64, high: u64, user: bool, variables: Vec<Variable>) -> Function {
        Function {
            name: name.into(),
            low_pc: low,
            high_pc: high,
            decl_file: 0,
            decl_line: 1,
            frame_base: Some(Location::Register("x29".into())),
            return_type: None,
            variables,
            prologue_end: None,
            user,
        }
    }

    fn view(
        name: &str,
        kind: VariableKind,
        address: Option<u64>,
        storage: Option<Storage>,
    ) -> VariableView {
        VariableView {
            name: name.into(),
            type_name: "int".into(),
            kind,
            value: ValueText::Value("1".into()),
            address,
            size: 4,
            children: Vec::new(),
            changed: false,
            storage,
        }
    }

    #[test]
    fn groups_follow_lines_and_functions() {
        let debug = DebugInfo {
            functions: vec![
                function("_start", 0x1000, 0x1008, false, Vec::new()),
                function("main", 0x1008, 0x1020, true, Vec::new()),
            ],
            ..Default::default()
        };
        let code = [
            instruction(0x1000, None),
            instruction(0x1004, None),
            instruction(0x1008, Some(3)),
            instruction(0x100c, Some(3)),
            instruction(0x1010, Some(4)),
            instruction(0x1014, Some(3)),
        ];
        let layout = MachineLayout::new(&code, Some(&debug));
        assert_eq!(layout.groups.len(), 4);
        assert_eq!(layout.rows.len(), 10);
        assert_eq!(layout.groups[1].line, Some(3));
        assert_eq!((layout.groups[1].start, layout.groups[1].end), (2, 4));
        assert_eq!(layout.instruction_rows[4], 7);
        assert_eq!(layout.group_of_instruction(5), Some(3));
        assert_eq!(layout.first_header_for_line(3), Some(3));
        assert_eq!(
            unlined_group_label(&layout.groups[0]),
            "_start: runtime code without C source"
        );
    }

    #[test]
    fn chips_name_frame_slots_registers_and_globals() {
        let slot = Storage::RegisterOffset {
            register: "x29".into(),
            offset: -4,
        };
        let chip = location_chip(&view(
            "count",
            VariableKind::Local,
            Some(0x1ffdc),
            Some(slot),
        ))
        .unwrap();
        assert_eq!(chip.text, "[x29\u{2212}4]");
        assert_eq!(
            chip.target,
            ChipTarget::Memory {
                address: 0x1ffdc,
                size: 4
            }
        );
        let register = Some(Storage::Register("x0".into()));
        let chip = location_chip(&view("value", VariableKind::Parameter, None, register)).unwrap();
        assert_eq!(chip.target, ChipTarget::Register("x0".into()));
        let chip = location_chip(&view(
            "total",
            VariableKind::Global,
            Some(0xa000),
            Some(Storage::Static),
        ))
        .unwrap();
        assert_eq!(chip.text, "global 0x0000A000");
        let chip = location_chip(&view(
            "counter",
            VariableKind::Local,
            Some(0xa004),
            Some(Storage::Static),
        ))
        .unwrap();
        assert_eq!(chip.text, "static 0x0000A004");
        let chip = location_chip(&view("[1]", VariableKind::Element, Some(0x1ffe0), None)).unwrap();
        assert_eq!(chip.text, "0x0001FFE0");
        assert!(location_chip(&view("gone", VariableKind::Local, None, None)).is_none());
    }

    #[test]
    fn unavailable_reasons_read_as_fragments() {
        assert_eq!(
            unavailable_text("Prologue not finished."),
            "unavailable: prologue not finished"
        );
        assert_eq!(
            unavailable_text("PC is outside"),
            "unavailable: PC is outside"
        );
    }

    #[test]
    fn snapped_breakpoints_toggle_their_stored_line() {
        let stored = [(4, Some(5)), (9, Some(9))];
        assert_eq!(breakpoint_line_to_toggle(5, stored), 4);
        assert_eq!(breakpoint_line_to_toggle(9, stored), 9);
        assert_eq!(breakpoint_line_to_toggle(7, stored), 7);
        // A breakpoint stored on the line itself wins over one that snapped to it.
        assert_eq!(
            breakpoint_line_to_toggle(5, [(4, Some(5)), (5, Some(5))]),
            5
        );
    }

    fn set(lines: &[usize]) -> std::collections::BTreeSet<usize> {
        lines.iter().copied().collect()
    }

    #[test]
    fn breakpoints_follow_inserted_and_deleted_lines() {
        let old = "a\nb\nc\nd\ne\n";
        // Insert two lines after b: c, d and e move down by two.
        let new = "a\nb\nx\ny\nc\nd\ne\n";
        assert_eq!(
            shift_breakpoint_lines(old, new, &set(&[1, 2, 3, 5])),
            set(&[1, 2, 5, 7])
        );
        // Delete c and d: a breakpoint on them is dropped, e moves up.
        let new = "a\nb\ne\n";
        assert_eq!(
            shift_breakpoint_lines(old, new, &set(&[2, 3, 4, 5])),
            set(&[2, 3])
        );
        // Editing inside a line keeps every breakpoint.
        let new = "a\nb\nC changed\nd\ne\n";
        assert_eq!(
            shift_breakpoint_lines(old, new, &set(&[3, 4])),
            set(&[3, 4])
        );
        // Splitting a line with Enter keeps the breakpoint on its first half.
        let new = "a\nb\nc1\nc2\nd\ne\n";
        assert_eq!(
            shift_breakpoint_lines(old, new, &set(&[3, 4])),
            set(&[3, 5])
        );
        // A blank line typed above a breakpoint moves it down.
        let new = "\na\nb\nc\nd\ne\n";
        assert_eq!(
            shift_breakpoint_lines(old, new, &set(&[1, 5])),
            set(&[2, 6])
        );
        // Identical text changes nothing.
        assert_eq!(shift_breakpoint_lines(old, old, &set(&[2])), set(&[2]));
    }
}
